### ISSUE TITLE
error

### ISSUE THREAD

**Issue by utkarsh7860** [SaiJeevanPuchakayala/NewsApi#1]
return ["--port=%d" % self.port] + self.service_args
TypeError: %d format: a number is required, not str
 giving the above error in line 45

**Comment by SaiJeevanPuchakayala** [comment]
> return ["--port=%d" % self.port] + self.service_args
> TypeError: %d format: a number is required, not str
> giving the above error in line 45

i don't find any line of code at line number 45.

**Comment by utkarsh7860** [comment]
Yeah, sorry i finished it before there was no any error I was doing a
stupid mistake.
I apologize for raising the issue with looking on it carefully.
Thanks for replying
